# Generated by Django 5.2.17 on 2026-09-07 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='break_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='休憩秒数'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('role', models.CharField(choices=[('member', 'メンバー'), ('manager', 'マネージャー')], default='member', max_length=10, verbose_name='役割')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='attendance.project', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'プロジェクトメンバー',
                'verbose_name_plural': 'プロジェクトメンバー',
                'ordering': ['project__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_membership')],
            },
        ),
    ]
